# The name of the workflow.
name: Sign Test

# Trigger this workflow on a push
on: [push]

env:
  FILE_NAME: hello.exe

# Defines a single job named "build-and-sign"
jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            include:
                - image: debian:stable
                #- image: debian:testing
    name: CodeSigner Test
    steps:
      # 1) Check out the source code so that the workflow can access it.
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install osslsigncode and ca-certificates
        run: sudo apt-get install --yes --no-install-recommends osslsigncode ca-certificates

      # 3) Create Artifact Directory to store signed and unsigned artifact files
      - name: Create Artifacts Directory
        shell: bash
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifacts

      - name: Create Input file for test signing
        shell: bash
        # run: |
        #   mkdir -p ${GITHUB_WORKSPACE}/example
        #   echo 'Write-Output -InputObject "Happy Signing From ESigner.com!"' > ${GITHUB_WORKSPACE}/example/${{env.FILE_NAME}}
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/example
          ls -la
          cp --verbose ${{env.FILE_NAME}} ${GITHUB_WORKSPACE}/example/${{env.FILE_NAME}}

      # 5) This is the step where the created JAR (artifact) files will be signed with CodeSignTool.
      - name: Sign Artifact with CodeSignTool
        #uses: sslcom/esigner-codesign@develop
        uses: sslcom/esigner-codesign@main
        with:
          # Sign and timestamp code object.
          command: sign
          # SSL.com account username
          username: ${{ secrets.ES_USERNAME }}
          # SSL.com account password.
          password: ${{ secrets.ES_PASSWORD }}
          # Credential ID for signing certificate.
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          # OAuth TOTP Secret (https://www.ssl.com/how-to/automate-esigner-ev-code-signing)
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          # Path of code object to be signed. (DLL, JAR, EXE, MSI files vb... )
          file_path: ${GITHUB_WORKSPACE}/example/${{env.FILE_NAME}}
          # Directory where signed code object(s) will be written.
          output_path: ${GITHUB_WORKSPACE}/artifacts
          # Scan code before sign
          malware_block: false
          # Environment Name, For Production 'PROD' or For Staging 'TEST'
          environment_name: TEST

      - name: Sanity Tests
        shell: bash
        run: |
          ls -la
          ls -la ./SSLcom-DEV.crt
          ls -la ${GITHUB_WORKSPACE}/example/${{env.FILE_NAME}}
          ls -la ./artifacts/${{env.FILE_NAME}}
          ls -la /etc/ssl/certs/ca-certificates.crt

      ## ssl.com demo certificate authority file (CAfile): SSLcom-DEV.crt
      ## https://github.com/SSLcom/esigner-codesign/issues/8
      - name: Verify Signature using osslsigncode
        shell: bash
        run: |
          osslsigncode verify -CAfile ./SSLcom-DEV.crt -in ./artifacts/${{env.FILE_NAME}}

      # 6) This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete
      - name: Upload Signed Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.FILE_NAME}}
          path: ./artifacts/${{env.FILE_NAME}}
